### PR TITLE
Create oscam_11399-emu_r766.patch

### PR DESCRIPTION
**Pull request by Sign-in-and**
[oscam-emu.zip](https://github.com/oscam-emu/oscam-emu/files/1711174/oscam-emu.zip)

### CODE REVIEW

**Comment by nautilus7** [comment]
This is not the proper way to submit the changes needed for 11399, or any changes.

**Comment by Sign-in-and** [comment]
kenne nur SVN , habe keine Erfahrung mit GIT --> 

only know SVN, have no experience with GIT

**Comment by oscam-emu** [comment]
Hi, @Sign-in-and, can you email me please?

(the mail is listed in readme)

**Comment by Sign-in-and** [comment]
Weshalb?

Von: oscam-emu [mailto:notifications@github.com]
Gesendet: Montag, 12. Februar 2018 01:29
An: oscam-emu/oscam-emu <oscam-emu@noreply.github.com>
Cc: Sign-in-and <Logiball@boardrebellen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [oscam-emu/oscam-emu] Create oscam_11399-emu_r766.patch (#258)


Hi, @Sign-in-and<https://github.com/sign-in-and>, can you email me please?

(the mail is listed in readme)

**Pull request closed without merging**
