### PR TITLE
fixe of recent changes in svn11289

### PR DESCRIPTION
**Pull request by ceco2000**

### CODE REVIEW

**Comment by docea37** [comment]
hi ceco2000 
oscam-emu.patch (--- CMakeLists.txt	(revision 11289) ) with Turksat 42e tandberg no opening

**Comment by nautilus7** [comment]
Yes, that's because you have to incorporate my pull request as well. That fixes tandberg. I'll update my pull request shortly to make it easier for builders.

**Comment by ceco2000** [comment]
Thank you in advance nautilus7.

**Comment by docea37** [comment]
nautilus7 thank you

**Pull request closed without merging**
