### PR TITLE
Tandberg ecm and emm algorithm fix

### PR DESCRIPTION
**Pull request by nautilus7**
fix for new tandberg algo:
-ECM_TAG_CW_DESCRIPTOR: add new tag 0xED
-EMM_TAG_SECURITY_TABLE_DESCRIPTOR E4: add new mode 0x01
-EMM_TAG_EVENT_ENTITLEMENT_DESCRIPTOR E1: add new mode 0x01

### CODE REVIEW

**Comment by nautilus7** [comment]
Looking further into the tandberg ecm code and while preparing the code for emm (key auto update) to work for new algorithm, I noticed this:

All ecm keys are written and read in softcam.key as "T entid 01 xxxxxxxxxxxxxxxx". This **01** is not used anywhere in the code and it's hard-written, without serving any purpose.

So, why not use different index (00, 01, 02, etc) to allow multiple keys with the same entid (entitlement) in the softcam.key???

We could use "00" for the old keys that are used in the initial (old) ecm algorithm, "01" for the keys used in the newer algorithm, and so on, depending on the nanoTag of the ecm algorithm.

This is easy to implement and I am willing to do so. What do you think?

**Comment by nautilus7** [comment]
#212

**Comment by melo77** [comment]
I ask if is possible update caid 1010 whith newcamd ? I have seen problems

if set .       user   au = 0 newcamd work all ok 
while
if set           user au = 1  or au = emulator oscam crach killed need restart

this is debug 255 crasch:
01:51:02 596EE516 c (reader) emulator [emu] EMM: reader 1010 match since emmpi d has no provid -> SEND!
01:51:02 596EE516 c (newcamd) AU enabled for user newbox on reader emulator
01:51:02 596EE516 c (newcamd) send 15 bytes to client
01:51:02 596EE516 c (newcamd) 00 0D 00 00 00 00 00 00 00 00 00 00 E1 00 00

01:51:02 596EE516 c (newcamd) nmr(): len=2, errno=0
01:51:02 596EE516 c (newcamd) received 5 bytes from client
01:51:02 596EE516 c (newcamd) 00 00 E3 00 00
01:51:02 596EE516 c (newcamd) client[77B46530].newbox nfilts=1, filt.caid=1010
01:51:02 596EE516 c (newcamd) client caid 0: 1010
01:51:02 596EE516 c (newcamd) search server provid 0: 000000

**Comment by nautilus7** [comment]
Hi, I don't see where the problem is from your log. And it's definitely not related to these changes I made, because I didn't touch anything related to newcamd.

If something is wrong it has to do with tandberg or/and other crypt systems in general and already existed before my patch. Better open a new issue and report there.

**Comment by sculpneo** [comment]
i think same issue again, turksat 42e fx channels are close, can you fix it?

**Pull request merged**
