### PR TITLE
trunk sync 11742 - 11748

### PR DESCRIPTION
**Pull request by WXbet**
- revert icam V9 back to 798
- remove emu streamrelay server
- use libdvbcsa in module-emulator-powervu

It might make sense to increase the EMU version number to 800 after merging this PR.

### CODE REVIEW

**Comment by WXbet** [comment]
> Anyway, I will merge latest svn to master branch.
Okay I wait until your merge is done. You need severeal changes for libdvbcsa, that I can bringin via PR after your merge.

Give me a sign please.

**Comment by WXbet** [comment]
@oscam-emu : https://github.com/oscam-emu/oscam-patched/pull/113

**Comment by tromoto** [comment]
I've tried on cortexa15 and aarch64 --> no luck (silent death, even debug does not help much). -O0 to -O2.

**Comment by WXbet** [comment]
Then you do something wrong.

**Comment by tromoto** [comment]
I know:) always:), ok let me try with less ambitious EXTRA_OECMAKE

**Comment by tromoto** [comment]
It seems the branch libdvbcsa fails (1st glance) with
CMake Error at CMakeLists.txt:473 (string):
|   string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
|   command.

If it happens only to me, sorry

**Comment by WXbet** [comment]
Hey @tromoto,
I don't know what you are doing, what build system, what build commands and options. You only share a error onliner. How do you expect people to help you?

**Comment by WXbet** [comment]
@oscam-emu : https://github.com/oscam-emu/oscam-patched/pull/114

**Pull request closed without merging**
