### PR TITLE
Support the latest oscam trunk r11734 & more.

### PR DESCRIPTION
**Pull request by ohmza**
- Support the latest oscam trunk r11734
- Fix POLLRDHUP compiling errors on macOS
- Fix all gcc 13.2 compiling warnings
- Fix unused function compiling warnings on clang 14

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
@ohmza 
Can you please update the pull request

**Comment by ohmza** [comment]
@AbuBaniaz The previous one should work with the latest r11732 as oscam trunk r11732 doesn't change anything on emu related part. However, I upload a new one as it contains a preliminary fix for unused functions build warning when clang is used as a compiler.

There are more work needed to be done in order to fix all build warnings when clang is used as a compiler, for example, the flag -fno-schedule-insns needed to be removed as clang doesn't support it. Hence, I need to talk to oscam-emu dev before proceeding this removal.

**Comment by ohmza** [comment]
@AbuBaniaz The previous one should work with the latest r11732 as oscam trunk r11732 doesn't change anything on emu related part. However, I upload a new one as it contains a preliminary fix for unused functions build warning when clang is used as a compiler.

There are more work needed to be done in order to fix all build warnings when clang is used as a compiler, for example, the flag -fno-schedule-insns needed to be removed as clang doesn't support it. Hence, I need to talk to oscam-emu dev before proceeding this removal.

**Comment by AbuBaniaz** [comment]
@oscam-emu 
We would be very grateful if you could review and merge these. Many thanks in advance

**Pull request closed without merging**
